title: RustFest.eu
email: team@rustfest.eu
description: >
  A Rust Community conference travelling all around Europe.

baseurl: "" # the subpath of the site, e.g. /blog
url: "https://www.rustfest.eu" # the base hostname & protocol for the site
metaKeywords: "rust, conf, rustfest, rustfesteu, conference, programming language"
social:
  twitter: rustfest
  github: rustfesteu
  facebook: rustfest
socialImageSrc: "/assets/favicons/logo.png"

location:
  venue: "Espace Saint-Martin"
  impl_days: "Mozilla Paris"
  city: "Paris"
  country: "France"

dates:
  year: "2018"
  talks: "Saturday, May 26th"
  workshops: "Sunday, May 27th"
  impl_days: "Monday, May 28th and<br>Tuesday, May 29th"
  impl_days_no_br: "Monday, May 28th and Tuesday, May 29th"

event:
  assets: "/assets/paris/"


# Page Settings
owner: "asquera Event UG"

collections:
  sessions:
    permalink: /:collection/:path
    output: true
  people:
    permalink: /:collection/:path
    output: true
  sponsors:
    permalink: /:collection/:path
    # They have their own link.
    output: false

defaults:
  - scope:
      type: sessions
    values:
      layout: session
  - scope:
      type: people
    values:
      layout: person

# mailinglist
mailchimp:
  server: asquera.us13.list-manage.com
  user: 7945052bc1ecc432bff53c079
  id: 5929ff51d6

exclude:
  - /vendor

# Build settings
markdown: kramdown

permalink: /blog/:title

# Plugins
plugins:
  - jekyll-redirect-from
